version: '2'
services:
    tngms-app:
        image: tngms
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@tngms-oracle:1521:tngms
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
